site_name: 'DecentHolograms Wiki'
site_description: 'Wiki of the DecentHolograms plugin'
site_author: 'decentsoftware-eu contributors'
site_url: 'https://docs.andre601.ch/DecentHolograms-Wiki' # TODO: Change to wiki.decentholograms.eu if used.

copyright: |
  Documentation licensed under the <a href="https://github.com/DecentSoftware-eu/DecentHolograms-Wiki/blob/main/LICENSE">GNU GPL v3.0 License</a>.

docs_dir: 'docs/'

repo_name: 'DecentHolograms'
repo_url: 'https://github.com/DecentSoftware-eu/DecentHolograms'

theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'assets/images/favicons/android-chrome-512x512.png'
  logo: 'assets/images/favicons/android-chrome-512x512.png'
  icon:
    repo: 'octicons/mark-github-16'
  palette:
    scheme: 'slate'
    primary: 'custom'
  features:
    - 'navigation.tabs'
    - 'navigation.tabs.sticky'
    - 'navigation.footer'
    - 'navigation.indexes'
    - 'content.code.copy'

watch:
  - theme

extra_css:
  - 'assets/stylesheets/theme.css'

extra_javascript:
  - 'assets/js/github-release.js'

plugins:
  - search
  - glightbox

markdown_extensions:
  # Already included extensions
  - admonition
  - attr_list
  - toc:
      permalink: true
      toc_depth: 3
  # PyMDownX extensions
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  # Neoteroi Cards extension
  - neoteroi.cards

nav:
  - index.md
  - General:
    - general/setup.md
    - general/compatibility.md
    - 'Format & Colors':
      - general/format-and-colors/index.md
      - general/format-and-colors/colors.md
    - Commands:
      - general/commands/index.md
      - general/commands/hologram.md
      - general/commands/hologram-line.md
      - general/commands/hologram-pages.md
    - Configuration:
      - general/configuration/index.md
      - general/configuration/config.md
      - general/configuration/animation.md
      - general/configuration/features.md
      - general/configuration/hologram.md
      - general/configuration/lang.md
    - Example Holograms:
      - general/examples/index.md
      - general/examples/example-demo.md
      - general/examples/example-entity.md
      - general/examples/example-recipe-with-offsets.md
      - general/examples/example-tree.md
      - general/examples/example-actions.md
    - general/animations.md
    - general/actions.md
    - general/flags.md
  - API:
    - api/get-started.md
    - api/basic-usage.md
  - Spigot: 'http://decentholograms.eu/'
  - Discord: 'https://discord.decentsoftware.eu/'